// src/webcomponents/widgets/tabs_view/OhaeTabItemButton.ts
import { Color } from "../../utils/Color";
import { OhaeButtonView } from "../input_view/OhaeButtonView";

export type Side = 'top' | 'bottom' | 'left' | 'right';

export class OhaeTabItemButtonView extends OhaeButtonView {
    public static readonly ATTRIBUTES: string[] = [
		'side',
		'icon',
		'current',
		'backgroundColor',
	];
	protected static readonly STYLES: string = `
		<style>
			:host {
				display: flex;
				width: 100%;
				max-height: 26px;
				min-height: 26px;
				padding: 0px;
				margin: 0px;
			}			

			.button {
				display: flex;
				align-items: center;
	
				background-color: var(--button-bg, #333);
				color: var(--button-color, #ddd);
				width: 100%;
				min-width: 20px;
				gap: 1px; /* Отступ между иконкой и текстом */
			}

			:host([side="top"]) .button {
				border-radius: 6px 6px 0 0;
				border: solid var(--button-border, #222) 1px;
				box-shadow: inset 0 -3px 3px rgba(0, 0, 0, 0.1);
				border-bottom: 0px;
			}
			:host([side="bottom"]) .button {
				border-radius: 0 0 6px 6px;
				border: solid var(--button-border, #222) 1px;
				box-shadow: inset 0 2px 2px rgba(0, 0, 0, 0.1);
				border-top: 0px;
			}
			:host([side="left"]) .button {
				border-radius: 6px 0 0 6px;
				border: solid var(--button-border, #222) 1px;
				box-shadow: inset -2px 0 2px rgba(0, 0, 0, 0.1);
				border-right: 0px;
			}				
			:host([side="right"]) .button {
				border-radius: 0 6px 6px 0;
				border: solid var(--button-border, #222) 1px;
				box-shadow: inset 2px 0 2px rgba(0, 0, 0, 0.1);
				border-left: 0px;
			}

			:host([current]) .button {
				background-color: var(--button-bg-active, #444);
			}
			:host([side="top"][current]) .button {
				border-bottom: 1px solid #415e9c;
			}
			:host([side="bottom"][current]) .button {
				border-top: 1px solid #415e9c;
			}

			:host([side="left"][current]) .button {
				border-right: 1px solid #415e9c;
			}				
			:host([side="right"][current]) .button {
				border-left: 1px solid #415e9c;
			}
				
			.button:active {
				background-color: var(--button-bg-active, #444);
			}
			:host([side="top"]) .button:active {
				transform: translateY(4px);
				height: calc(100% - 4px);
			}
			:host([side="bottom"]) .button:active {
				height: calc(100% - 4px);
			}
			:host([side="left"]) .button:active {
				transform: translateX(8px);
				width: calc(100% - 8px);
			}
			:host([side="right"]) .button:active {
				white-space: nowrap;
				width: calc(100% - 8px);
			}

			.button:hover {
				background-color: var(--button-bg-hover, #3b3b3b);
			}

			.button:disabled,
			.button[disabled] {
				background-color: var(--button-bg-disabled, #282828);
			}


			.icon-wrapper {
				display: flex;
				/* flex-shrink: 0; */
				position: relative;
				justify-content: center;
				align-items: center;
				width: 16px;
				height: 20px;
			}

			.icon {
				font-size: 14px; /* Размер иконки, подстрой по желанию */
				justify-content: flex-start;
				align-items: flex-start;			
			}

			.label {
				flex-grow: 1;
				min-width: 0;
				width: auto;
				text-align: center;
				white-space: nowrap;
				overflow: hidden;
				text-overflow: ellipsis;
			}
			:host([side="left"]) .label {
				display: none;
			}
			:host([side="right"]) .label {
				display: none;
			}
		</style>
	` + this.FONT_AVESOME;
	protected static readonly HTML: string = `
		<button class='button'>
			<span class='icon-wrapper'>
				<span class='icon fa fa-check'></span>
			</span>
			<span class='label'>button</span>
		</button>
	`;

	protected override async createCallback() {
		this.markAsInitDataReady();
        await super.createCallback();
        this.applyAttributes(OhaeTabItemButtonView.ATTRIBUTES);

		// const icon = document.createElement('span');
		// icon.classList.add('fa', 'fa-check');
		// this.innerHTML = ''; // На всякий случай очистим контент
		// this.appendChild(icon);

		// const fontAwesomeScript = document.querySelector('script');
		// console.log('tick', fontAwesomeScript)

		
		//   const id = setInterval(() => {
		// 	console.log('setInterval');
		// 	const fontAwesomeFont = document.querySelector('#fa-v5-font-face');
		// 	const fontAwesomeMain = document.querySelector('#fa-main');
		// 	if (fontAwesomeScript && fontAwesomeFont && fontAwesomeMain) {
		// 		this.shadowRoot!.appendChild(fontAwesomeScript.cloneNode());
		// 		this.shadowRoot!.appendChild(fontAwesomeFont.cloneNode());
		// 		this.shadowRoot!.appendChild(fontAwesomeMain.cloneNode());
		// 	  clearInterval(id);
		// 	//   this.label = "qwe"
		// 	console.log('tick')

		// 	}
		//   }, 200);
	}

	static get observedAttributes() {
        return [...super.observedAttributes, ...this.ATTRIBUTES];
    }

	public static getSide(value: string | null): Side {
		value = value ?? 'top';
		const sideValue = ['top', 'bottom', 'left', 'right'].includes(value) ? value : 'top';
		return sideValue as Side;
	}

	get icon(): string {
        return this.getAttribute('icon') ?? 'fa fa-plus';
    }
    set icon(value: string) {
		const icon = this.shadowRoot?.querySelector('.icon') as HTMLElement;
		const stringValue = (value ?? '').toString();
		this.setAttribute('icon', stringValue);
		if(icon) icon.className = `icon fa ${stringValue}`;
    }

	get label(): string {
        return this.getAttribute('label') ?? '';
    }
    set label(value: string | number | null) {
		const label = this.shadowRoot?.querySelector('.button')?.querySelector('.label') as HTMLElement;
		// console.log('button', 1, this)
		// console.log('button', 2, this.shadowRoot)
		// console.log('button', 3, this.shadowRoot?.querySelector('.button'))
		// console.log('label', label)
		const stringValue = (value ?? '').toString();
		this.setAttribute('label', stringValue);
		if(label) label.innerHTML = stringValue;
    }

	get side(): Side {
		const value = this.getAttribute('side');
        return  OhaeTabItemButtonView.getSide(value);
    }
    set side(value: Side | null) {
		value = OhaeTabItemButtonView.getSide(value)
		this.setAttribute('side', value);
    }

	get current(): boolean { 
		return this.getAttribute('current') === 'true';
	}
    set current(value: boolean | string | null) {
		value = value === true || value === 'true';
        if (value) {
            this.setAttribute('current', 'true');
        } else {
            this.removeAttribute('current');
        }
	}
	set backgroundColor(value: string | Color | null){
		if(!value) return;
		const color = typeof value === 'string' ? new Color(value) : value;
		this.style.setProperty("--button-bg", color.brightness(0.7).hex);
		this.style.setProperty("--button-bg-hover", color.brightness(0.9).hex);
		this.style.setProperty("--button-bg-active", color.hex);
		this.style.setProperty("--button-color", color.shift(128).hex);
		this.style.setProperty("--button-border", color.brightness(0.4).hex);
	}

	get backgroundColor(): Color {
		return new Color(this.getAttribute('backgroundColor')??"#333");
	}	
}
customElements.define('ohae-tab-button', OhaeTabItemButtonView);

declare module "../../OhaeViewOptions" {
    interface IOhaeViewOptions {
		side?: Side;
		icon?: string;
		current?: string | boolean;
		backgroundColor?: string;
    }
}

// src/components/tabs/OhaeTabItemButton.svelte
<svelte:options customElement={{ tag: "ohae-tab-button" }} />

<script lang="ts">
    import { useShadowTheme } from "../../lib/useShadowTheme";
    import { Color } from "../../lib/Color";

    export type TabButtonSide = "top" | "bottom" | "left" | "right";

    let {
        label = "",
        icon = "fa-plus",
        side = "top" as TabButtonSide,
        current = false,
        disabled = false,
        backgroundColor = "#333333", // Default hex color from WC
        flex = undefined,
        minWidth = undefined,
        minHeight = "26px", // Default from WC for top/bottom
        width = undefined, // Default width is auto/100% based on side
        height = undefined, // Default height is 26px for top/bottom, 100% for left/right
        className = undefined,
        customStyle = "",
    }: {
        label?: string | number;
        icon?: string;
        side?: TabButtonSide;
        current?: boolean;
        disabled?: boolean;
        backgroundColor?: string;
        flex?: number | "none" | string;
        minWidth?: number | string;
        minHeight?: number | string;
        width?: number | string;
        height?: number | string;
        className?: string;
        customStyle?: string;
    } = $props();

    useShadowTheme(() => $host().shadowRoot);

    $effect(() => {
        const host = $host();
        if (!host) return;
        const color = new Color(backgroundColor); // Assumes backgroundColor is a hex string
        host.style.setProperty("--button-bg", color.brightness(0.7).hex);
        host.style.setProperty("--button-bg-hover", color.brightness(0.9).hex);
        host.style.setProperty("--button-bg-active", color.hex);
        host.style.setProperty("--button-color", color.shift(128).hex); // Ensure Color.shift exists
        host.style.setProperty("--button-border", color.brightness(0.4).hex);

        // Apply flex, width, height to the host directly
        if (flex !== undefined) {
            host.style.flex = String(flex);
        } else {
            host.style.flex =
                side === "left" || side === "right" ? "none" : "1";
        }

        if (minWidth !== undefined)
            host.style.minWidth =
                typeof minWidth === "number" ? `${minWidth}px` : minWidth;
        if (minHeight !== undefined)
            host.style.minHeight =
                typeof minHeight === "number" ? `${minHeight}px` : minHeight;

        if (side === "left" || side === "right") {
            host.style.width =
                typeof width === "number" ? `${width}px` : (width ?? "auto");
            host.style.height =
                typeof height === "number" ? `${height}px` : (height ?? "100%");
            // For left/right, max-height might not be fixed like top/bottom
        } else {
            // top or bottom
            host.style.width =
                typeof width === "number" ? `${width}px` : (width ?? "100%");
            host.style.height =
                typeof height === "number" ? `${height}px` : (height ?? "26px");
            host.style.maxHeight = "26px"; // From WC
        }
    });

    const showLabel = $derived(!(side === "left" || side === "right"));
</script>

<button
    type="button"
    class="button {className}"
    class:current
    class:side-top={side === "top"}
    class:side-bottom={side === "bottom"}
    class:side-left={side === "left"}
    class:side-right={side === "right"}
    {disabled}
    style={customStyle}
    aria-pressed={current}
    aria-label={String(label) || "Tab button"}
    tabindex="0"
>
    {#if icon && icon !== "false" && icon !== "null"}
        <span class="icon-wrapper">
            <span class="icon fa {icon.startsWith('fa-') ? icon : 'fa-' + icon}"
            ></span>
        </span>
    {/if}
    {#if showLabel && label}
        <span class="label">{label}</span>
    {/if}
</button>

<style>
    /* Ensure FontAwesome is available, e.g., via useShadowTheme or direct import if needed */
    /* @import url("../../assets/fontawesome-free-6.7.2-web/css/all.min.css"); */

    :host {
        display: flex;
        padding: 0px;
        margin: 0px;
        box-sizing: border-box;
        /* flex, width, height, min/max are set by $effect */
    }

    .button {
        display: flex;
        align-items: center;
        justify-content: center;
        box-sizing: border-box;
        border: 1px solid var(--button-border, #222);
        background-color: var(--button-bg, #333);
        color: var(--button-color, #ddd);
        width: 100%;
        height: 100%;
        gap: 5px;
        padding: 0 8px;
        cursor: pointer;
        font-family: inherit;
        font-size: inherit;
        text-align: center;
        white-space: nowrap;
        overflow: hidden;
    }

    /* Side-specific styles from WC */
    .button.side-top {
        border-radius: 6px 6px 0 0;
        box-shadow: inset 0 -3px 3px rgba(0, 0, 0, 0.1);
        border-bottom-width: 0;
    }
    .button.side-bottom {
        border-radius: 0 0 6px 6px;
        box-shadow: inset 0 2px 2px rgba(0, 0, 0, 0.1);
        border-top-width: 0;
    }
    .button.side-left {
        border-radius: 6px 0 0 6px;
        box-shadow: inset -2px 0 2px rgba(0, 0, 0, 0.1);
        border-right-width: 0;
        /* flex-direction: column; /* If icon and label are stacked */
    }
    .button.side-right {
        border-radius: 0 6px 6px 0;
        box-shadow: inset 2px 0 2px rgba(0, 0, 0, 0.1);
        border-left-width: 0;
        /* flex-direction: column; */
    }

    /* Current state */
    .button.current {
        background-color: var(--button-bg-active, #444);
        position: relative; /* For pseudo-elements or z-index if needed */
    }
    .button.side-top.current {
        border-bottom: 1px solid var(--button-bg-active); /* Match active bg for seamless look */
    }
    .button.side-bottom.current {
        border-top: 1px solid var(--button-bg-active);
    }
    .button.side-left.current {
        border-right: 1px solid var(--button-bg-active);
    }
    .button.side-right.current {
        border-left: 1px solid var(--button-bg-active);
    }

    /* Active (pressed) state */
    .button:active:not(:disabled) {
        background-color: var(
            --button-bg-active,
            #444
        ); /* Can be same as current or slightly different */
    }
    .button.side-top:active:not(:disabled) {
        transform: translateY(2px);
    }
    .button.side-left:active:not(:disabled) {
        transform: translateX(2px);
    }
    /* For side-right and side-bottom, active transform might look odd, WC didn't always have symmetrical transforms */
    .button.side-right:active:not(:disabled) {
        transform: translateX(-2px);
    } /* Mirroring left */

    .button:hover:not(:disabled) {
        background-color: var(--button-bg-hover, #3b3b3b);
    }

    .button:disabled {
        background-color: var(
            --button-bg-disabled,
            #282828
        ) !important; /* Ensure override */
        color: #666 !important;
        cursor: not-allowed;
        transform: none !important; /* No active transform when disabled */
    }

    .icon-wrapper {
        display: inline-flex;
        justify-content: center;
        align-items: center;
        flex-shrink: 0;
    }
    .icon {
        font-size: 1em; /* Or fixed like 14px */
    }
    .label {
        flex-grow: 1;
        min-width: 0;
        overflow: hidden;
        text-overflow: ellipsis;
    }
</style>
